### ISSUE TITLE
编译通过，访问出错

### ISSUE THREAD

**Issue by longyangsky** [wmui/essay#35]
database connect successed
(node:796) UnhandledPromiseRejectionWarning: MongoError: command find requires authentication
    at queryCallback (E:\nodejs_Study\essay\node_modules\mongodb-core\lib\cursor.js:248:25)
    at E:\nodejs_Study\essay\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:796) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

访问
http://127.0.0.1:3000/
错误
TypeError
Cannot read property 'nickname' of undefined

**Comment by hsiangleev** [comment]
@longyangsky 同样的错误，请问有解决办法吗

**Comment by wmui** [comment]
建议mongodb 4.0 以上，node 8.12.0以上运行

**Comment by wmui** [comment]
@longyangsky package.json 去掉 dev 的 nodemon配置 `cross-env NODE_ENV= development node server/index.js`
