### ISSUE TITLE
3.0稳定版本预计什么时候能出来呀，持续关注中

### ISSUE THREAD

**Issue by yoog568** [wmui/essay#37]

**Comment by wmui** [comment]
就冲你这个关注，我定当快马加鞭、夜以继日、不负众望尽快开发，3.0主要包括以下功能：

1. 完整的权限管理系统
2. 支持分类管理、标签管理、单页管理
3. 可视化安装界面
4. 优化编辑器
5. 数据备份系统（支持远程和本地）

ps: 由于业务较忙，所以无法给出确定日期，但我保证会维护下去的
