### ISSUE TITLE
能不能告知项目搭建的步骤

### ISSUE THREAD

**Issue by wuweikd** [wmui/essay#38]
我非常喜欢这个项目，但是我不太理解怎么搭建起来的；我查看过nuxt.js的搭建过程；也查看过express的搭建过程，但是我不知道你是怎么合并前后端到同一个工程里面，谢谢了

**Comment by wmui** [comment]
nuxt本身是一个前后端同构框架，你只需要按照目录结构写前后端代码即可，集成的工作是nuxt做的，后端你可以选择express、koa或者其他框架
